# Generated by Django 2.2.1 on 2019-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='games_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guess',
            name='image_character',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
