# Generated by Django 2.2.1 on 2019-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190515_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='question',
            field=models.ManyToManyField(blank=True, to='game.Guess'),
        ),
        migrations.AlterField(
            model_name='score',
            name='players_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
