# Generated by Django 2.2.1 on 2019-05-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190515_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='question',
        ),
    ]
