# Generated by Django 2.2.1 on 2019-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_score_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='question',
            field=models.ManyToManyField(blank=True, through='game.Answer', to='game.Guess'),
        ),
    ]
