# Generated by Django 2.2.1 on 2019-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190521_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='char_character',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='image_character',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
