# Generated by Django 2.2.1 on 2019-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190625_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guessed_right',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guessed_wrong1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guessed_wrong2',
            field=models.CharField(max_length=256),
        ),
    ]
