# Generated by Django 2.2.1 on 2019-06-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190625_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='image_character',
        ),
    ]
